coverage:
  status:
    project:
      default:
        target: 90%
    patch:
      components:
        target: 90%
        flags:
          - components
      system:
        target: 90%
        flags:
          - system
      tokens:
        target: 90%
        flags:
          - tokens

comment:
  layout: 'reach, diff, flags, files'

flags:
  - name: components
    paths:
      - /packages/components/src/
  - name: system
    paths:
      - /packages/system/src/
  - name: tokens
    paths:
      - /packages/tokens/src/
