import type { MigrationManifest } from '../types.js';

// Hand-written v18 manifest (DST-1543 delivery step 2). Codegen (step 3) will
// derive `slots`, `restructures`, `removedComponents` and the swap class
// strings from the Theme-type/theme-rui diff between the previous major and
// the current one; regenerating this file and diffing it against this
// hand-written version is codegen's own acceptance test.
//
// Data provenance:
// - slots: extracted from packages/system/src/types/theme.ts (v18)
// - swap oldClasses: theme-rui at git tag @marigold/components@17.9.1
// - swap newSource / scaffold loadBearing: current theme-rui
// - warning links: GitHub permalinks pinned to commit 946dc9f30 (on
//   beta-release; line numbers verified against it). Codegen should
//   re-resolve these against the final release tag.
// Calendar and RangeCalendar share the same slot set in v18.
const calendarSlots = [
  'calendar',
  'calendarContainer',
  'calendarMonth',
  'calendarListboxButton',
  'calendarCell',
  'calendarControllers',
  'calendarHeader',
  'calendarGrid',
  'calendarHeading',
  'calendarPresets',
  'select',
];

export const v18: MigrationManifest = {
  schemaVersion: 1,
  version: 'v18',
  stylesReferenceUrl:
    'https://github.com/marigold-ui/marigold/blob/946dc9f30/themes/theme-rui/src/components',
  slots: {
    Accordion: [
      'container',
      'item',
      'header',
      'panel',
      'content',
      'icon',
      'actions',
    ],
    ActionBar: ['container', 'selection', 'count', 'toolbar', 'clearButton'],
    Badge: null,
    Breadcrumbs: ['container', 'item', 'link', 'current'],
    Button: null,
    Card: [
      'container',
      'header',
      'title',
      'description',
      'content',
      'footer',
      'media',
    ],
    CloseButton: null,
    Collapsible: ['container', 'trigger', 'content'],
    ContextualHelp: ['trigger', 'container', 'title', 'description', 'content'],
    DateField: ['segment', 'field', 'input', 'action'],
    Dialog: [
      'closeButton',
      'container',
      'header',
      'content',
      'actions',
      'title',
      'description',
    ],
    Divider: null,
    Drawer: [
      'overlay',
      'closeButton',
      'container',
      'header',
      'title',
      'description',
      'content',
      'actions',
    ],
    Tray: [
      'overlay',
      'container',
      'dragHandle',
      'header',
      'title',
      'description',
      'content',
      'actions',
    ],
    Field: null,
    BooleanField: ['container', 'description'],
    Headline: null,
    Popover: null,
    HelpText: ['container', 'icon'],
    IconButton: null,
    Checkbox: ['container', 'label', 'checkbox', 'group'],
    Switch: ['container', 'track', 'thumb'],
    Input: ['input', 'icon', 'action'],
    Keyboard: null,
    Label: null,
    List: ['ol', 'ul', 'item'],
    Link: null,
    ListBox: [
      'container',
      'list',
      'item',
      'section',
      'header',
      'label',
      'description',
    ],
    Menu: [
      'container',
      'section',
      'item',
      'button',
      'label',
      'description',
      'keyboard',
    ],
    Modal: null,
    Panel: [
      'root',
      'header',
      'title',
      'description',
      'actions',
      'content',
      'collapsible',
      'collapsibleHeader',
      'collapsibleTitle',
      'collapsibleDescription',
      'collapsibleContent',
      'collapsibleIcon',
      'footer',
    ],
    Page: ['root', 'header', 'title', 'description', 'actions', 'content'],
    Pagination: [
      'container',
      'navigationButton',
      'pageButton',
      'icon',
      'ellipsis',
    ],
    ProgressCircle: ['container', 'loader', 'label'],
    Radio: ['container', 'label', 'radio', 'group'],
    Slider: ['container', 'track', 'thumb', 'output', 'selectedTrack'],
    Select: ['select', 'icon'],
    SelectList: [
      'container',
      'list',
      'item',
      'label',
      'description',
      'indicator',
      'action',
    ],
    NumberField: ['group', 'stepper', 'input'],
    SectionMessage: ['container', 'icon', 'title', 'description', 'content'],
    Table: [
      'table',
      'head',
      'column',
      'body',
      'footer',
      'row',
      'cell',
      'dragHandle',
      'dragPreview',
      'dragPreviewCounter',
      'dropIndicator',
      'editablePopover',
      'editTrigger',
      'editCancel',
      'editSave',
    ],
    LegacyTable: [
      'table',
      'headerRow',
      'header',
      'thead',
      'body',
      'row',
      'cell',
    ],
    Tag: ['container', 'tag', 'listItems', 'closeButton', 'showMore'],
    TagField: ['trigger', 'tagGroup', 'listItems', 'container'],
    Text: null,
    TextArea: null,
    Tooltip: ['container', 'arrow'],
    Toast: [
      'toast',
      'title',
      'description',
      'closeButton',
      'icon',
      'content',
      'bottom-left',
      'bottom-right',
      'top-left',
      'top-right',
      'top',
      'bottom',
      'action',
    ],
    Tabs: [
      'container',
      'tabsList',
      'tabsListScroll',
      'tabpanel',
      'tab',
      'tabIndicator',
    ],
    Underlay: null,
    Calendar: calendarSlots,
    RangeCalendar: calendarSlots,
    DatePicker: null,
    DateRangePicker: null,
    ComboBox: ['icon', 'mobileTrigger'],
    Autocomplete: ['mobileTrigger'],
    Loader: ['container', 'loader', 'label'],
    FileField: [
      'container',
      'dropZone',
      'dropZoneContent',
      'dropZoneLabel',
      'item',
      'itemLabel',
      'itemDescription',
      'itemRemove',
    ],
    EmptyState: ['container', 'title', 'description', 'action'],
    ToggleButton: ['group', 'button'],
    SegmentedControl: ['group', 'list', 'field', 'option', 'indicator'],
    Sidebar: [
      'root',
      'overlay',
      'modal',
      'closeButton',
      'header',
      'nav',
      'footer',
      'toggle',
      'separator',
      'groupLabel',
      'navPanel',
      'navLink',
      'backButton',
      'content',
    ],
    TopNavigation: ['container', 'start', 'middle', 'end'],
  },
  restructures: [{ component: 'Card', primarySlot: 'container' }],
  scaffolds: [
    {
      name: 'BooleanField',
      requiredBy: ['Checkbox', 'Switch'],
      reason:
        'new in v18: `Checkbox` and `Switch` render a `BooleanField` wrapper internally (label/description grid), and a theme without its styles throws at runtime',
      // BooleanField is purely structural (grid columns, col-start), so both
      // slots are load-bearing and carry the v18 layout verbatim.
      loadBearing: {
        container: `{
  base: 'grid gap-x-2',
  variants: {
    variant: {
      default: 'grid-cols-[auto_1fr]',
      settings: 'grid-cols-[1fr_auto]',
    },
  },
  defaultVariants: {
    variant: 'default',
  },
}`,
        description: `{
  base: 'mt-0.5',
  variants: {
    variant: {
      default: 'col-start-2',
      settings: 'col-start-1',
    },
  },
  defaultVariants: {
    variant: 'default',
  },
}`,
      },
    },
  ],
  removedComponents: ['MultiSelect'],
  swaps: [
    {
      component: 'Checkbox',
      slot: 'container',
      oldClasses: ['cursor-pointer read-only:cursor-default gap-2'],
      newSource: `{
  base: [
    'grid grid-cols-[auto_1fr] gap-x-2 items-start',
    'cursor-pointer read-only:cursor-default',
    'group-data-[booleanfield]/booleanfield:grid-cols-subgrid group-data-[booleanfield]/booleanfield:col-span-full',
    'group-data-[orientation=vertical]/checkboxgroup:py-1',
    'group-data-[orientation=horizontal]/checkboxgroup:px-1.5',
  ],
}`,
    },
    {
      component: 'Switch',
      slot: 'container',
      oldClasses: [
        'disabled:cursor-not-allowed disabled:text-disabled-foreground',
      ],
      newSource: `{
  base: [
    'grid gap-x-2 items-center',
    'disabled:cursor-not-allowed disabled:text-disabled',
    'group-data-booleanfield/booleanfield:grid-cols-subgrid group-data-booleanfield/booleanfield:col-span-full',
  ],
  variants: {
    variant: {
      default: 'grid-cols-[auto_1fr]',
      settings: 'grid-cols-[1fr_auto]',
    },
  },
  defaultVariants: {
    variant: 'default',
  },
}`,
    },
  ],
  structureWarnings: [
    {
      component: 'Switch',
      text: 'v18 changes the Switch DOM: the toggle/label order and wrapper structure changed (grid layout, BooleanField wrapper for descriptions). CSS selectors targeting the old DOM (e.g. generated BEM selectors) must be reviewed. New DOM: https://github.com/marigold-ui/marigold/blob/946dc9f30/packages/components/src/Switch/Switch.tsx',
    },
    {
      component: 'Card',
      text: 'v18 restructures the Card DOM into compound slots (Card.Header/Title/Description/Content/Footer/Media). CSS selectors targeting the old single-container DOM must be reviewed. New DOM: https://github.com/marigold-ui/marigold/blob/946dc9f30/packages/components/src/Card/Card.tsx',
    },
  ],
  // Application-code changes. Only lexically decidable renames/removals are
  // edits; everything needing a structural JSX move (Tooltip open, Card
  // compound) or a design decision stays a warning.
  jsx: {
    renames: [
      { component: 'Inset', from: 'space', to: 'p' },
      { component: 'Inset', from: 'spaceX', to: 'px' },
      { component: 'Inset', from: 'spaceY', to: 'py' },
      {
        component: 'FileField',
        from: 'acceptedFileType',
        to: 'acceptedFileTypes',
        wrapInArray: true,
      },
      {
        component: 'FileTrigger',
        from: 'acceptedFileType',
        to: 'acceptedFileTypes',
        wrapInArray: true,
      },
    ],
    memberRenames: [
      { object: 'Tabs', from: 'TabPanel', to: 'Panel' },
      { object: 'SelectList', from: 'Item', to: 'Option' },
    ],
    // v18 icon migration (@marigold/icons became a lucide-react proxy).
    // Mapping extracted from the official table in
    // .changeset/iconography-docs.md — never hand-typed. Identity mappings
    // (Search, Check, ...) are omitted; unaliased imports are rewritten as
    // `New as Old` per the release-notes recommendation.
    importRenames: [
      { package: '@marigold/icons', from: 'Add', to: 'Plus' },
      { package: '@marigold/icons', from: 'BurgerMenu', to: 'Menu' },
      { package: '@marigold/icons', from: 'CircleChecked', to: 'CircleDot' },
      { package: '@marigold/icons', from: 'CircleUnchecked', to: 'Circle' },
      { package: '@marigold/icons', from: 'Delete', to: 'Trash2' },
      { package: '@marigold/icons', from: 'Filter', to: 'ListFilter' },
      { package: '@marigold/icons', from: 'IconMore', to: 'Ellipsis' },
      { package: '@marigold/icons', from: 'Remove', to: 'Minus' },
      {
        package: '@marigold/icons',
        from: 'SettingDots',
        to: 'EllipsisVertical',
      },
      { package: '@marigold/icons', from: 'SquareChecked', to: 'SquareCheck' },
      { package: '@marigold/icons', from: 'SquareUnchecked', to: 'Square' },
      { package: '@marigold/icons', from: 'Accessible', to: 'Accessibility' },
      { package: '@marigold/icons', from: 'AutoRenew', to: 'RefreshCcw' },
      { package: '@marigold/icons', from: 'Banned', to: 'Ban' },
      { package: '@marigold/icons', from: 'BatteryEmpty', to: 'BatteryLow' },
      { package: '@marigold/icons', from: 'BatteryHalf', to: 'BatteryMedium' },
      { package: '@marigold/icons', from: 'Bus', to: 'BusFront' },
      {
        package: '@marigold/icons',
        from: 'Direction',
        to: 'SquareArrowUpRight',
      },
      { package: '@marigold/icons', from: 'Email', to: 'Mail' },
      { package: '@marigold/icons', from: 'EventDate', to: 'Calendar1' },
      { package: '@marigold/icons', from: 'Exclamation', to: 'TriangleAlert' },
      { package: '@marigold/icons', from: 'Feedback', to: 'MessageSquareMore' },
      { package: '@marigold/icons', from: 'Food', to: 'Utensils' },
      { package: '@marigold/icons', from: 'Home', to: 'House' },
      { package: '@marigold/icons', from: 'Marker', to: 'MapPin' },
      { package: '@marigold/icons', from: 'MobilePhone', to: 'Smartphone' },
      { package: '@marigold/icons', from: 'MobileSignal', to: 'SignalHigh' },
      {
        package: '@marigold/icons',
        from: 'Notification',
        to: 'MessageSquareWarning',
      },
      { package: '@marigold/icons', from: 'Parking', to: 'CircleParking' },
      { package: '@marigold/icons', from: 'Reports', to: 'FileText' },
      { package: '@marigold/icons', from: 'Required', to: 'Asterisk' },
      { package: '@marigold/icons', from: 'ResaleLogbook', to: 'BookOpenText' },
      { package: '@marigold/icons', from: 'Spinner', to: 'Loader' },
      { package: '@marigold/icons', from: 'Thumb', to: 'ThumbsUp' },
      { package: '@marigold/icons', from: 'Cancel', to: 'CircleX' },
      { package: '@marigold/icons', from: 'Edit', to: 'Pencil' },
      {
        package: '@marigold/icons',
        from: 'ExportFile',
        to: 'SquareArrowOutUpRight',
      },
      { package: '@marigold/icons', from: 'FormatBold', to: 'Bold' },
      { package: '@marigold/icons', from: 'FormatItalic', to: 'Italic' },
      { package: '@marigold/icons', from: 'FormatSize', to: 'ALargeSmall' },
      { package: '@marigold/icons', from: 'HighlightOff', to: 'Power' },
      { package: '@marigold/icons', from: 'Location', to: 'LocateFixed' },
      { package: '@marigold/icons', from: 'Logout', to: 'LogOut' },
      { package: '@marigold/icons', from: 'Picture', to: 'Image' },
      { package: '@marigold/icons', from: 'ResaleEdit', to: 'Cog' },
      { package: '@marigold/icons', from: 'Restart', to: 'RotateCcw' },
      { package: '@marigold/icons', from: 'RotateLeft', to: 'RotateCcw' },
      { package: '@marigold/icons', from: 'RotateRight', to: 'RotateCw' },
      { package: '@marigold/icons', from: 'Sort', to: 'ChevronsUpDown' },
      { package: '@marigold/icons', from: 'SortDown', to: 'ChevronDown' },
      { package: '@marigold/icons', from: 'SortUp', to: 'ChevronUp' },
      { package: '@marigold/icons', from: 'Stop', to: 'CircleStop' },
      { package: '@marigold/icons', from: 'Underlined', to: 'Underline' },
      { package: '@marigold/icons', from: 'Zoom', to: 'ZoomIn' },
      { package: '@marigold/icons', from: 'Deal', to: 'BadgePercent' },
      { package: '@marigold/icons', from: 'Membership', to: 'IdCardLanyard' },
      { package: '@marigold/icons', from: 'Pickup', to: 'Store' },
      { package: '@marigold/icons', from: 'Price', to: 'Euro' },
      { package: '@marigold/icons', from: 'Seat', to: 'Armchair' },
      { package: '@marigold/icons', from: 'Selling', to: 'Tag' },
      { package: '@marigold/icons', from: 'Cart', to: 'ShoppingCart' },
      { package: '@marigold/icons', from: 'Group', to: 'UsersRound' },
      { package: '@marigold/icons', from: 'Id', to: 'IdCard' },
      { package: '@marigold/icons', from: 'SmilieDissatisfied', to: 'Frown' },
      { package: '@marigold/icons', from: 'SmilieNeutral', to: 'Meh' },
      { package: '@marigold/icons', from: 'SmilieSatisfied', to: 'Smile' },
      {
        package: '@marigold/icons',
        from: 'SmilieVeryDissatisfied',
        to: 'Angry',
      },
      { package: '@marigold/icons', from: 'SmilieVerySatisfied', to: 'Laugh' },
      { package: '@marigold/icons', from: 'User', to: 'UserRound' },
      { package: '@marigold/icons', from: 'Share', to: 'Share2' },
      {
        package: '@marigold/icons',
        from: 'Print',
        to: 'Printer',
        note: 'missing from the official mapping table — Printer is the Lucide equivalent',
      },
    ],
    removals: [
      {
        component: 'TextField',
        prop: 'min',
        note: 'unsupported in v18; use NumberField for numeric constraints, see https://github.com/marigold-ui/marigold/blob/946dc9f30/packages/components/src/NumberField/NumberField.tsx#L22',
      },
      {
        component: 'TextField',
        prop: 'max',
        note: 'unsupported in v18; use NumberField for numeric constraints, see https://github.com/marigold-ui/marigold/blob/946dc9f30/packages/components/src/NumberField/NumberField.tsx#L22',
      },
    ],
    warnings: [
      {
        component: 'Switch',
        prop: 'size',
        value: 'large',
        text: 'the default v18 theme removed size="large". If the intent was a settings-style switch, use variant="settings"; a standalone theme defining its own size variants can keep the prop. See https://github.com/marigold-ui/marigold/blob/946dc9f30/packages/components/src/Switch/Switch.tsx#L111',
      },
      {
        component: 'Tooltip',
        prop: 'open',
        text: 'the open prop moved to Tooltip.Trigger in v18 — move it manually. See https://github.com/marigold-ui/marigold/blob/946dc9f30/packages/components/src/Tooltip/TooltipTrigger.tsx#L21',
      },
      {
        component: 'Select',
        prop: 'width',
        value: 'fit',
        text: 'width="fit" was removed in v18 — choose an explicit width (design decision). See https://github.com/marigold-ui/marigold/blob/946dc9f30/packages/components/src/Select/Select.tsx#L52-L59',
      },
      {
        component: 'ComboBox',
        prop: 'width',
        value: 'fit',
        text: 'width="fit" was removed in v18 — choose an explicit width (design decision). See https://github.com/marigold-ui/marigold/blob/946dc9f30/packages/components/src/ComboBox/ComboBox.tsx#L43',
      },
      {
        component: 'Autocomplete',
        prop: 'width',
        value: 'fit',
        text: 'width="fit" was removed in v18 — choose an explicit width (design decision). See https://github.com/marigold-ui/marigold/blob/946dc9f30/packages/components/src/Autocomplete/Autocomplete.tsx#L124',
      },
      {
        component: 'Multiselect',
        text: 'Multiselect was removed in v18 — use TagField (different API), migrate manually. See https://github.com/marigold-ui/marigold/blob/946dc9f30/packages/components/src/TagField/TagField.tsx#L43',
      },
      {
        component: 'SelectList',
        prop: 'onChange',
        text: 'the onChange signature changed in v18: single mode passes (key: Key | null), multiple mode passes (keys: Key[]) instead of a Selection set — update the handler. See https://github.com/marigold-ui/marigold/blob/946dc9f30/packages/components/src/SelectList/SelectList.tsx#L137-L145',
      },
      {
        component: 'Card',
        prop: 'pt',
        text: 'one-sided Card paddings were removed in v18 — only p/px/py remain; move the padding into the card content (e.g. an Inset or the compound Card slots). See https://github.com/marigold-ui/marigold/blob/946dc9f30/packages/components/src/Card/Card.tsx#L64-L77',
      },
      {
        component: 'Card',
        prop: 'pb',
        text: 'one-sided Card paddings were removed in v18 — only p/px/py remain; move the padding into the card content (e.g. an Inset or the compound Card slots). See https://github.com/marigold-ui/marigold/blob/946dc9f30/packages/components/src/Card/Card.tsx#L64-L77',
      },
      {
        component: 'Card',
        prop: 'pl',
        text: 'one-sided Card paddings were removed in v18 — only p/px/py remain; move the padding into the card content (e.g. an Inset or the compound Card slots). See https://github.com/marigold-ui/marigold/blob/946dc9f30/packages/components/src/Card/Card.tsx#L64-L77',
      },
      {
        component: 'Card',
        prop: 'pr',
        text: 'one-sided Card paddings were removed in v18 — only p/px/py remain; move the padding into the card content (e.g. an Inset or the compound Card slots). See https://github.com/marigold-ui/marigold/blob/946dc9f30/packages/components/src/Card/Card.tsx#L64-L77',
      },
    ],
  },
};
