<div>
  <MenuTrigger>
    <Button>...</Button>

    <Menu>
      <Menu.Item></Menu.Item>
      <Menu.Item></Menu.Item>
      <Menu.Item></Menu.Item>
    </Menu>
  </MenuTrigger>
  ;
  <Menu.Button>
    ...
    <Menu>
      <Menu.Item></Menu.Item>
      <Menu.Item></Menu.Item>
      <Menu.Item></Menu.Item>
    </Menu>
  </Menu.Button>
  ;
</div>;
