module.exports = {
  printWidth: 80,
  arrowParens: 'avoid',
  singleQuote: true,
  trailingComma: 'es5',
  useTabs: false,
  tabWidth: 2,
  plugins: [
    require.resolve('@trivago/prettier-plugin-sort-imports'),
    require.resolve('prettier-plugin-tailwindcss'),
  ],
  importOrder: [
    '^node:(.*)$',
    '^react/(.*)$',
    '^next/(.*)$',
    '^\\.storybook/(.*)$',
    '^@react-aria/(.*)$',
    '^@react-stately/(.*)$',
    '^@react-types/(.*)$',
    '^@marigold/(.*)$',
    '^@/theme/(.*)$',
    '^@/ui/(.*)$',
    '^@components/(.*)$',
    '^[./]',
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
};
