export interface Venue {
  id: string;
  name: string;
  city: string;
  region: string;
  country: string;
  type: string;
  setting: string;
  capacity: string;
  rating: string;
  events: number;
  status: string;
  rate: string;
}

export const venues: Venue[] = [
  {
    id: 'astra',
    name: 'Astra Kulturhaus',
    city: 'Berlin',
    region: 'Berlin',
    country: 'Germany',
    type: 'Club',
    setting: 'Indoor',
    capacity: '1,500',
    rating: '4.4',
    events: 12,
    status: 'Available',
    rate: '€2,400',
  },
  {
    id: 'gruenspan',
    name: 'Grünspan',
    city: 'Hamburg',
    region: 'Hamburg',
    country: 'Germany',
    type: 'Club',
    setting: 'Indoor',
    capacity: '1,200',
    rating: '4.2',
    events: 8,
    status: 'Booked',
    rate: '€2,100',
  },
  {
    id: 'backstage',
    name: 'Backstage',
    city: 'Munich',
    region: 'Bavaria',
    country: 'Germany',
    type: 'Club',
    setting: 'Indoor',
    capacity: '900',
    rating: '4.3',
    events: 10,
    status: 'Available',
    rate: '€1,700',
  },
  {
    id: 'palladium',
    name: 'Palladium',
    city: 'Cologne',
    region: 'North Rhine-Westphalia',
    country: 'Germany',
    type: 'Concert Hall',
    setting: 'Indoor',
    capacity: '4,000',
    rating: '4.6',
    events: 18,
    status: 'Held',
    rate: '€5,600',
  },
  {
    id: 'capitol',
    name: 'Capitol',
    city: 'Hanover',
    region: 'Lower Saxony',
    country: 'Germany',
    type: 'Concert Hall',
    setting: 'Indoor',
    capacity: '1,350',
    rating: '4.1',
    events: 6,
    status: 'Available',
    rate: '€2,300',
  },
  {
    id: 'zakk',
    name: 'zakk',
    city: 'Dusseldorf',
    region: 'North Rhine-Westphalia',
    country: 'Germany',
    type: 'Club',
    setting: 'Indoor',
    capacity: '1,000',
    rating: '4.0',
    events: 7,
    status: 'Available',
    rate: '€1,800',
  },
  {
    id: 'batschkapp',
    name: 'Batschkapp',
    city: 'Frankfurt',
    region: 'Hesse',
    country: 'Germany',
    type: 'Club',
    setting: 'Indoor',
    capacity: '1,500',
    rating: '4.3',
    events: 9,
    status: 'Booked',
    rate: '€2,500',
  },
  {
    id: 'longhorn',
    name: 'LKA Longhorn',
    city: 'Stuttgart',
    region: 'Baden-Württemberg',
    country: 'Germany',
    type: 'Concert Hall',
    setting: 'Indoor',
    capacity: '1,100',
    rating: '4.2',
    events: 5,
    status: 'Available',
    rate: '€2,000',
  },
  {
    id: 'waldbuehne',
    name: 'Waldbühne',
    city: 'Berlin',
    region: 'Berlin',
    country: 'Germany',
    type: 'Open Air',
    setting: 'Outdoor',
    capacity: '22,000',
    rating: '4.8',
    events: 15,
    status: 'Held',
    rate: '€18,000',
  },
  {
    id: 'loreley',
    name: 'Loreley',
    city: 'St. Goarshausen',
    region: 'Rhineland-Palatinate',
    country: 'Germany',
    type: 'Open Air',
    setting: 'Outdoor',
    capacity: '15,000',
    rating: '4.7',
    events: 11,
    status: 'Available',
    rate: '€12,000',
  },
  {
    id: 'huxleys',
    name: 'Huxleys Neue Welt',
    city: 'Berlin',
    region: 'Berlin',
    country: 'Germany',
    type: 'Club',
    setting: 'Indoor',
    capacity: '1,600',
    rating: '4.4',
    events: 13,
    status: 'Available',
    rate: '€2,600',
  },
  {
    id: 'columbiahalle',
    name: 'Columbiahalle',
    city: 'Berlin',
    region: 'Berlin',
    country: 'Germany',
    type: 'Concert Hall',
    setting: 'Indoor',
    capacity: '3,500',
    rating: '4.5',
    events: 16,
    status: 'Booked',
    rate: '€4,900',
  },
  {
    id: 'docks',
    name: 'Docks',
    city: 'Hamburg',
    region: 'Hamburg',
    country: 'Germany',
    type: 'Club',
    setting: 'Indoor',
    capacity: '1,500',
    rating: '4.1',
    events: 9,
    status: 'Available',
    rate: '€2,300',
  },
  {
    id: 'ewerk',
    name: 'E-Werk',
    city: 'Cologne',
    region: 'North Rhine-Westphalia',
    country: 'Germany',
    type: 'Concert Hall',
    setting: 'Indoor',
    capacity: '3,000',
    rating: '4.4',
    events: 14,
    status: 'Held',
    rate: '€4,200',
  },
  {
    id: 'tanzbrunnen',
    name: 'Tanzbrunnen',
    city: 'Cologne',
    region: 'North Rhine-Westphalia',
    country: 'Germany',
    type: 'Open Air',
    setting: 'Outdoor',
    capacity: '12,000',
    rating: '4.6',
    events: 10,
    status: 'Available',
    rate: '€9,500',
  },
  {
    id: 'muffathalle',
    name: 'Muffathalle',
    city: 'Munich',
    region: 'Bavaria',
    country: 'Germany',
    type: 'Concert Hall',
    setting: 'Indoor',
    capacity: '1,200',
    rating: '4.3',
    events: 8,
    status: 'Available',
    rate: '€2,200',
  },
  {
    id: 'zitadelle',
    name: 'Zitadelle Spandau',
    city: 'Berlin',
    region: 'Berlin',
    country: 'Germany',
    type: 'Open Air',
    setting: 'Outdoor',
    capacity: '8,000',
    rating: '4.5',
    events: 12,
    status: 'Booked',
    rate: '€7,000',
  },
  {
    id: 'turbinenhalle',
    name: 'Turbinenhalle',
    city: 'Oberhausen',
    region: 'North Rhine-Westphalia',
    country: 'Germany',
    type: 'Concert Hall',
    setting: 'Indoor',
    capacity: '2,500',
    rating: '4.0',
    events: 6,
    status: 'Available',
    rate: '€3,400',
  },
  {
    id: 'tempodrom',
    name: 'Tempodrom',
    city: 'Berlin',
    region: 'Berlin',
    country: 'Germany',
    type: 'Concert Hall',
    setting: 'Indoor',
    capacity: '3,800',
    rating: '4.6',
    events: 17,
    status: 'Available',
    rate: '€5,200',
  },
  {
    id: 'so36',
    name: 'SO36',
    city: 'Berlin',
    region: 'Berlin',
    country: 'Germany',
    type: 'Club',
    setting: 'Indoor',
    capacity: '800',
    rating: '4.2',
    events: 11,
    status: 'Held',
    rate: '€1,500',
  },
  {
    id: 'uebel',
    name: 'Uebel & Gefährlich',
    city: 'Hamburg',
    region: 'Hamburg',
    country: 'Germany',
    type: 'Club',
    setting: 'Indoor',
    capacity: '800',
    rating: '4.4',
    events: 9,
    status: 'Available',
    rate: '€1,600',
  },
  {
    id: 'freiheit',
    name: 'Große Freiheit 36',
    city: 'Hamburg',
    region: 'Hamburg',
    country: 'Germany',
    type: 'Concert Hall',
    setting: 'Indoor',
    capacity: '1,500',
    rating: '4.3',
    events: 10,
    status: 'Booked',
    rate: '€2,400',
  },
  {
    id: 'tonhalle',
    name: 'Tonhalle',
    city: 'Munich',
    region: 'Bavaria',
    country: 'Germany',
    type: 'Concert Hall',
    setting: 'Indoor',
    capacity: '3,600',
    rating: '4.5',
    events: 15,
    status: 'Available',
    rate: '€4,800',
  },
  {
    id: 'zenith',
    name: 'Zenith',
    city: 'Munich',
    region: 'Bavaria',
    country: 'Germany',
    type: 'Arena',
    setting: 'Indoor',
    capacity: '6,000',
    rating: '4.4',
    events: 13,
    status: 'Held',
    rate: '€6,500',
  },
  {
    id: 'livemusichall',
    name: 'Live Music Hall',
    city: 'Cologne',
    region: 'North Rhine-Westphalia',
    country: 'Germany',
    type: 'Concert Hall',
    setting: 'Indoor',
    capacity: '1,600',
    rating: '4.2',
    events: 8,
    status: 'Available',
    rate: '€2,500',
  },
  {
    id: 'gloria',
    name: 'Gloria Theater',
    city: 'Cologne',
    region: 'North Rhine-Westphalia',
    country: 'Germany',
    type: 'Theater',
    setting: 'Indoor',
    capacity: '700',
    rating: '4.5',
    events: 7,
    status: 'Available',
    rate: '€1,400',
  },
  {
    id: 'zeche',
    name: 'Zeche Bochum',
    city: 'Bochum',
    region: 'North Rhine-Westphalia',
    country: 'Germany',
    type: 'Concert Hall',
    setting: 'Indoor',
    capacity: '900',
    rating: '4.1',
    events: 5,
    status: 'Booked',
    rate: '€1,700',
  },
  {
    id: 'mojo',
    name: 'Mojo Club',
    city: 'Hamburg',
    region: 'Hamburg',
    country: 'Germany',
    type: 'Club',
    setting: 'Indoor',
    capacity: '500',
    rating: '4.6',
    events: 12,
    status: 'Available',
    rate: '€1,200',
  },
  {
    id: 'schlachthof',
    name: 'Schlachthof',
    city: 'Wiesbaden',
    region: 'Hesse',
    country: 'Germany',
    type: 'Concert Hall',
    setting: 'Indoor',
    capacity: '1,500',
    rating: '4.0',
    events: 6,
    status: 'Held',
    rate: '€2,300',
  },
  {
    id: 'jahrhunderthalle',
    name: 'Jahrhunderthalle',
    city: 'Frankfurt',
    region: 'Hesse',
    country: 'Germany',
    type: 'Arena',
    setting: 'Indoor',
    capacity: '4,800',
    rating: '4.5',
    events: 14,
    status: 'Available',
    rate: '€6,000',
  },
  {
    id: 'wagenhallen',
    name: 'Wagenhallen',
    city: 'Stuttgart',
    region: 'Baden-Württemberg',
    country: 'Germany',
    type: 'Concert Hall',
    setting: 'Indoor',
    capacity: '1,800',
    rating: '4.3',
    events: 9,
    status: 'Available',
    rate: '€2,700',
  },
  {
    id: 'wizemann',
    name: 'Im Wizemann',
    city: 'Stuttgart',
    region: 'Baden-Württemberg',
    country: 'Germany',
    type: 'Concert Hall',
    setting: 'Indoor',
    capacity: '1,300',
    rating: '4.2',
    events: 7,
    status: 'Booked',
    rate: '€2,200',
  },
  {
    id: 'substage',
    name: 'Substage',
    city: 'Karlsruhe',
    region: 'Baden-Württemberg',
    country: 'Germany',
    type: 'Club',
    setting: 'Indoor',
    capacity: '700',
    rating: '4.1',
    events: 6,
    status: 'Available',
    rate: '€1,400',
  },
  {
    id: 'kesselhaus',
    name: 'Kesselhaus',
    city: 'Berlin',
    region: 'Berlin',
    country: 'Germany',
    type: 'Concert Hall',
    setting: 'Indoor',
    capacity: '900',
    rating: '4.3',
    events: 10,
    status: 'Available',
    rate: '€1,700',
  },
  {
    id: 'lanxess',
    name: 'Lanxess Arena',
    city: 'Cologne',
    region: 'North Rhine-Westphalia',
    country: 'Germany',
    type: 'Arena',
    setting: 'Indoor',
    capacity: '18,000',
    rating: '4.7',
    events: 20,
    status: 'Held',
    rate: '€16,000',
  },
  {
    id: 'barclays',
    name: 'Barclays Arena',
    city: 'Hamburg',
    region: 'Hamburg',
    country: 'Germany',
    type: 'Arena',
    setting: 'Indoor',
    capacity: '16,000',
    rating: '4.7',
    events: 19,
    status: 'Available',
    rate: '€15,000',
  },
  {
    id: 'columbiatheater',
    name: 'Columbia Theater',
    city: 'Berlin',
    region: 'Berlin',
    country: 'Germany',
    type: 'Theater',
    setting: 'Indoor',
    capacity: '1,000',
    rating: '4.2',
    events: 8,
    status: 'Available',
    rate: '€1,900',
  },
  {
    id: 'parkbuehne',
    name: 'Parkbühne',
    city: 'Leipzig',
    region: 'Saxony',
    country: 'Germany',
    type: 'Open Air',
    setting: 'Outdoor',
    capacity: '5,000',
    rating: '4.4',
    events: 9,
    status: 'Available',
    rate: '€4,500',
  },
  {
    id: 'taubertal',
    name: 'Taubertal Festival Ground',
    city: 'Rothenburg',
    region: 'Bavaria',
    country: 'Germany',
    type: 'Open Air',
    setting: 'Outdoor',
    capacity: '20,000',
    rating: '4.6',
    events: 4,
    status: 'Held',
    rate: '€14,000',
  },
  {
    id: 'markthalle',
    name: 'Markthalle',
    city: 'Hamburg',
    region: 'Hamburg',
    country: 'Germany',
    type: 'Club',
    setting: 'Indoor',
    capacity: '1,000',
    rating: '4.0',
    events: 7,
    status: 'Available',
    rate: '€1,800',
  },
  {
    id: 'gasometer',
    name: 'Gasometer',
    city: 'Vienna',
    region: 'Vienna',
    country: 'Austria',
    type: 'Concert Hall',
    setting: 'Indoor',
    capacity: '3,000',
    rating: '4.5',
    events: 12,
    status: 'Available',
    rate: '€4,300',
  },
  {
    id: 'arena-wien',
    name: 'Arena Wien',
    city: 'Vienna',
    region: 'Vienna',
    country: 'Austria',
    type: 'Club',
    setting: 'Indoor',
    capacity: '3,000',
    rating: '4.4',
    events: 10,
    status: 'Booked',
    rate: '€3,900',
  },
  {
    id: 'posthof',
    name: 'Posthof',
    city: 'Linz',
    region: 'Upper Austria',
    country: 'Austria',
    type: 'Concert Hall',
    setting: 'Indoor',
    capacity: '1,200',
    rating: '4.2',
    events: 6,
    status: 'Available',
    rate: '€2,200',
  },
  {
    id: 'rockhouse',
    name: 'Rockhouse',
    city: 'Salzburg',
    region: 'Salzburg',
    country: 'Austria',
    type: 'Club',
    setting: 'Indoor',
    capacity: '600',
    rating: '4.3',
    events: 5,
    status: 'Available',
    rate: '€1,500',
  },
  {
    id: 'pmk',
    name: 'PMK',
    city: 'Innsbruck',
    region: 'Tyrol',
    country: 'Austria',
    type: 'Club',
    setting: 'Indoor',
    capacity: '400',
    rating: '4.1',
    events: 4,
    status: 'Held',
    rate: '€1,100',
  },
  {
    id: 'stadthalle',
    name: 'Wiener Stadthalle',
    city: 'Vienna',
    region: 'Vienna',
    country: 'Austria',
    type: 'Arena',
    setting: 'Indoor',
    capacity: '16,000',
    rating: '4.6',
    events: 17,
    status: 'Available',
    rate: '€14,500',
  },
  {
    id: 'kaufleuten',
    name: 'Kaufleuten',
    city: 'Zurich',
    region: 'Zurich',
    country: 'Switzerland',
    type: 'Concert Hall',
    setting: 'Indoor',
    capacity: '1,000',
    rating: '4.4',
    events: 9,
    status: 'Available',
    rate: '€3,200',
  },
  {
    id: 'xtra',
    name: 'X-TRA',
    city: 'Zurich',
    region: 'Zurich',
    country: 'Switzerland',
    type: 'Concert Hall',
    setting: 'Indoor',
    capacity: '1,500',
    rating: '4.3',
    events: 11,
    status: 'Booked',
    rate: '€3,800',
  },
  {
    id: 'kaserne',
    name: 'Kaserne',
    city: 'Basel',
    region: 'Basel-Stadt',
    country: 'Switzerland',
    type: 'Club',
    setting: 'Indoor',
    capacity: '800',
    rating: '4.2',
    events: 6,
    status: 'Available',
    rate: '€2,600',
  },
  {
    id: 'hallenstadion',
    name: 'Hallenstadion',
    city: 'Zurich',
    region: 'Zurich',
    country: 'Switzerland',
    type: 'Arena',
    setting: 'Indoor',
    capacity: '15,000',
    rating: '4.7',
    events: 18,
    status: 'Held',
    rate: '€16,500',
  },
];

// Maps a booking status to the Badge variant used wherever a venue is shown,
// so the pick table and the committed report render status the same way.
export const statusVariant: Record<string, 'success' | 'warning' | 'default'> =
  {
    Available: 'success',
    Held: 'warning',
    Booked: 'default',
  };
