export interface Venue {
  id: string;
  name: string;
  city: string;
  region: string;
  type: string;
  capacity: string;
  status: string;
  rate: string;
}

export const venues: Venue[] = [
  {
    id: 'astra',
    name: 'Astra Kulturhaus',
    city: 'Berlin',
    region: 'Berlin',
    type: 'Club',
    capacity: '1,500',
    status: 'Available',
    rate: '€2,400',
  },
  {
    id: 'gruenspan',
    name: 'Grünspan',
    city: 'Hamburg',
    region: 'Hamburg',
    type: 'Club',
    capacity: '1,200',
    status: 'Booked',
    rate: '€2,100',
  },
  {
    id: 'backstage',
    name: 'Backstage',
    city: 'Munich',
    region: 'Bavaria',
    type: 'Club',
    capacity: '900',
    status: 'Available',
    rate: '€1,700',
  },
  {
    id: 'palladium',
    name: 'Palladium',
    city: 'Cologne',
    region: 'North Rhine-Westphalia',
    type: 'Concert Hall',
    capacity: '4,000',
    status: 'Held',
    rate: '€5,600',
  },
  {
    id: 'capitol',
    name: 'Capitol',
    city: 'Hanover',
    region: 'Lower Saxony',
    type: 'Concert Hall',
    capacity: '1,350',
    status: 'Available',
    rate: '€2,300',
  },
  {
    id: 'zakk',
    name: 'zakk',
    city: 'Dusseldorf',
    region: 'North Rhine-Westphalia',
    type: 'Club',
    capacity: '1,000',
    status: 'Available',
    rate: '€1,800',
  },
  {
    id: 'batschkapp',
    name: 'Batschkapp',
    city: 'Frankfurt',
    region: 'Hesse',
    type: 'Club',
    capacity: '1,500',
    status: 'Booked',
    rate: '€2,500',
  },
  {
    id: 'longhorn',
    name: 'LKA Longhorn',
    city: 'Stuttgart',
    region: 'Baden-Württemberg',
    type: 'Concert Hall',
    capacity: '1,100',
    status: 'Available',
    rate: '€2,000',
  },
  {
    id: 'waldbuehne',
    name: 'Waldbühne',
    city: 'Berlin',
    region: 'Berlin',
    type: 'Open Air',
    capacity: '22,000',
    status: 'Held',
    rate: '€18,000',
  },
  {
    id: 'loreley',
    name: 'Loreley',
    city: 'St. Goarshausen',
    region: 'Rhineland-Palatinate',
    type: 'Open Air',
    capacity: '15,000',
    status: 'Available',
    rate: '€12,000',
  },
  {
    id: 'huxleys',
    name: 'Huxleys Neue Welt',
    city: 'Berlin',
    region: 'Berlin',
    type: 'Club',
    capacity: '1,600',
    status: 'Available',
    rate: '€2,600',
  },
  {
    id: 'columbiahalle',
    name: 'Columbiahalle',
    city: 'Berlin',
    region: 'Berlin',
    type: 'Concert Hall',
    capacity: '3,500',
    status: 'Booked',
    rate: '€4,900',
  },
  {
    id: 'docks',
    name: 'Docks',
    city: 'Hamburg',
    region: 'Hamburg',
    type: 'Club',
    capacity: '1,500',
    status: 'Available',
    rate: '€2,300',
  },
  {
    id: 'ewerk',
    name: 'E-Werk',
    city: 'Cologne',
    region: 'North Rhine-Westphalia',
    type: 'Concert Hall',
    capacity: '3,000',
    status: 'Held',
    rate: '€4,200',
  },
  {
    id: 'tanzbrunnen',
    name: 'Tanzbrunnen',
    city: 'Cologne',
    region: 'North Rhine-Westphalia',
    type: 'Open Air',
    capacity: '12,000',
    status: 'Available',
    rate: '€9,500',
  },
  {
    id: 'muffathalle',
    name: 'Muffathalle',
    city: 'Munich',
    region: 'Bavaria',
    type: 'Concert Hall',
    capacity: '1,200',
    status: 'Available',
    rate: '€2,200',
  },
  {
    id: 'zitadelle',
    name: 'Zitadelle Spandau',
    city: 'Berlin',
    region: 'Berlin',
    type: 'Open Air',
    capacity: '8,000',
    status: 'Booked',
    rate: '€7,000',
  },
  {
    id: 'turbinenhalle',
    name: 'Turbinenhalle',
    city: 'Oberhausen',
    region: 'North Rhine-Westphalia',
    type: 'Concert Hall',
    capacity: '2,500',
    status: 'Available',
    rate: '€3,400',
  },
  {
    id: 'tempodrom',
    name: 'Tempodrom',
    city: 'Berlin',
    region: 'Berlin',
    type: 'Concert Hall',
    capacity: '3,800',
    status: 'Available',
    rate: '€5,200',
  },
  {
    id: 'so36',
    name: 'SO36',
    city: 'Berlin',
    region: 'Berlin',
    type: 'Club',
    capacity: '800',
    status: 'Held',
    rate: '€1,500',
  },
  {
    id: 'uebel',
    name: 'Uebel & Gefährlich',
    city: 'Hamburg',
    region: 'Hamburg',
    type: 'Club',
    capacity: '800',
    status: 'Available',
    rate: '€1,600',
  },
  {
    id: 'freiheit',
    name: 'Große Freiheit 36',
    city: 'Hamburg',
    region: 'Hamburg',
    type: 'Concert Hall',
    capacity: '1,500',
    status: 'Booked',
    rate: '€2,400',
  },
  {
    id: 'tonhalle',
    name: 'Tonhalle',
    city: 'Munich',
    region: 'Bavaria',
    type: 'Concert Hall',
    capacity: '3,600',
    status: 'Available',
    rate: '€4,800',
  },
  {
    id: 'zenith',
    name: 'Zenith',
    city: 'Munich',
    region: 'Bavaria',
    type: 'Arena',
    capacity: '6,000',
    status: 'Held',
    rate: '€6,500',
  },
  {
    id: 'livemusichall',
    name: 'Live Music Hall',
    city: 'Cologne',
    region: 'North Rhine-Westphalia',
    type: 'Concert Hall',
    capacity: '1,600',
    status: 'Available',
    rate: '€2,500',
  },
  {
    id: 'gloria',
    name: 'Gloria Theater',
    city: 'Cologne',
    region: 'North Rhine-Westphalia',
    type: 'Theater',
    capacity: '700',
    status: 'Available',
    rate: '€1,400',
  },
  {
    id: 'zeche',
    name: 'Zeche Bochum',
    city: 'Bochum',
    region: 'North Rhine-Westphalia',
    type: 'Concert Hall',
    capacity: '900',
    status: 'Booked',
    rate: '€1,700',
  },
  {
    id: 'mojo',
    name: 'Mojo Club',
    city: 'Hamburg',
    region: 'Hamburg',
    type: 'Club',
    capacity: '500',
    status: 'Available',
    rate: '€1,200',
  },
  {
    id: 'schlachthof',
    name: 'Schlachthof',
    city: 'Wiesbaden',
    region: 'Hesse',
    type: 'Concert Hall',
    capacity: '1,500',
    status: 'Held',
    rate: '€2,300',
  },
  {
    id: 'jahrhunderthalle',
    name: 'Jahrhunderthalle',
    city: 'Frankfurt',
    region: 'Hesse',
    type: 'Arena',
    capacity: '4,800',
    status: 'Available',
    rate: '€6,000',
  },
  {
    id: 'wagenhallen',
    name: 'Wagenhallen',
    city: 'Stuttgart',
    region: 'Baden-Württemberg',
    type: 'Concert Hall',
    capacity: '1,800',
    status: 'Available',
    rate: '€2,700',
  },
  {
    id: 'wizemann',
    name: 'Im Wizemann',
    city: 'Stuttgart',
    region: 'Baden-Württemberg',
    type: 'Concert Hall',
    capacity: '1,300',
    status: 'Booked',
    rate: '€2,200',
  },
  {
    id: 'substage',
    name: 'Substage',
    city: 'Karlsruhe',
    region: 'Baden-Württemberg',
    type: 'Club',
    capacity: '700',
    status: 'Available',
    rate: '€1,400',
  },
  {
    id: 'kesselhaus',
    name: 'Kesselhaus',
    city: 'Berlin',
    region: 'Berlin',
    type: 'Concert Hall',
    capacity: '900',
    status: 'Available',
    rate: '€1,700',
  },
  {
    id: 'lanxess',
    name: 'Lanxess Arena',
    city: 'Cologne',
    region: 'North Rhine-Westphalia',
    type: 'Arena',
    capacity: '18,000',
    status: 'Held',
    rate: '€16,000',
  },
  {
    id: 'barclays',
    name: 'Barclays Arena',
    city: 'Hamburg',
    region: 'Hamburg',
    type: 'Arena',
    capacity: '16,000',
    status: 'Available',
    rate: '€15,000',
  },
];

// Maps a booking status to the Badge variant used wherever a venue is shown,
// so the pick table and the committed report render status the same way.
export const statusVariant: Record<string, 'success' | 'warning' | 'default'> =
  {
    Available: 'success',
    Held: 'warning',
    Booked: 'default',
  };
