import { type InferPageType, loader } from 'fumadocs-core/source';
// @ts-ignore - Virtual module generated by fumadocs-mdx at build time
import { blog, docs } from 'fumadocs-mdx:collections/server';
import type { MDXContent } from 'mdx/types';

export interface DocsPageData {
  title: string;
  description?: string;
  caption?: string;
  order?: number;
  badge?: string;
  toc?: any;
  lastModified?: string;
  body: MDXContent;
  getText: (mode: 'processed' | 'raw') => Promise<string>;
}

export interface BlogPageData {
  title: string;
  description?: string;
  date: string | Date;
  type?: string;
  changed?: string[];
  body: MDXContent;
  toc?: any;
  getText: (mode: 'processed' | 'raw') => Promise<string>;
}

// See https://fumadocs.dev/docs/headless/source-api for more info
export const source = loader({
  baseUrl: '/',
  source: docs.toFumadocsSource(),
});

export const blogSource = loader({
  baseUrl: '/releases/blog',
  source: blog.toFumadocsSource(),
});

export function getPageImage(page: InferPageType<typeof source>) {
  const segments = [...page.slugs, 'image.png'];

  return {
    segments,
    url: `/og/docs/${segments.join('/')}`,
  };
}

export async function getLLMText(page: InferPageType<typeof source>) {
  const processed = await (page.data as DocsPageData).getText('processed');

  return `# ${page.data.title}

${processed}`;
}

/**
 * extract badges from pages for client sside use
 * called once during server-side rendering
 */
export function getBadgeMap(): Record<string, string> {
  const badgeMap: Record<string, string> = {};
  const pages = source.getPages();

  for (const page of pages) {
    const data = page.data as DocsPageData;
    if (data.badge) {
      badgeMap[page.url] = data.badge;
    }
  }

  return badgeMap;
}
