// Route handler for /manifest.json — the docs page index for AI agents and
// crawlers. Reads the pre-built file at .registry/manifest.json (generated by
// scripts/build-manifest.mjs).
//
// `await connection()` opts the route out of Next.js's static prerender pass,
// which avoids the Node 22+ undici × prerender Proxy bug
// (https://github.com/nodejs/undici/issues/4290). Vercel's CDN caches the
// response for the duration of `s-maxage` so the function only runs on cache
// miss / revalidation.
import manifest from '@/.registry/manifest.json';
import { connection } from 'next/server';

export const GET = async () => {
  await connection();
  return Response.json(manifest, {
    headers: {
      'Cache-Control':
        'public, max-age=0, s-maxage=31536000, stale-while-revalidate=86400',
    },
  });
};
