// @ts-nocheck
import { registry } from '../public/registry/registry.ts';
import { registrySchema } from '../public/registry/schema.ts';

const result = registrySchema.safeParse(registry);

if (!result.success) {
  console.error(result.error);
  process.exit(1);
}

let index = `// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"
import dynamic from 'next/dynamic';

export const Index: Record<string, any> = {
`;

console.log('huhu', result);

for (const item of result.data) {
  index += `
    "${item.name}": {
      name: "${item.name}",
        demo: dynamic(
        () => import('@/content/components/button/${item.name}.demo')
      ),
      ")),
    },`;
}

console.log(index);
