import React from 'react';
import Head from 'next/head';

import { Button, Stack, MarigoldProvider } from '@marigold/components';
import theme, { webFontUrl } from '@marigold/theme-b2b';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.gstatic.com" />
        {webFontUrl.map(url => (
          <link key={url} href={url} rel="stylesheet" />
        ))}
      </Head>

      <MarigoldProvider theme={theme}>
        <Stack space="xxlarge" alignX="center">
          <Button variant="primary">Hi!</Button>
        </Stack>
      </MarigoldProvider>
    </div>
  );
}
