// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import dynamic from 'next/dynamic';

export const registry = {
  'accordion-basic': {
    name: 'accordion-basic',
    demo: dynamic(
      () => import('@/content/components/accordion/accordion-basic.demo')
    ),
    file: 'content/components/accordion/accordion-basic.demo.tsx',
  },
  'horizontal-breakout': {
    name: 'horizontal-breakout',
    demo: dynamic(
      () => import('@/content/components/breakout/horizontal-breakout.demo')
    ),
    file: 'content/components/breakout/horizontal-breakout.demo.tsx',
  },
  'iframe-breakout': {
    name: 'iframe-breakout',
    demo: dynamic(
      () => import('@/content/components/breakout/iframe-breakout.demo')
    ),
    file: 'content/components/breakout/iframe-breakout.demo.tsx',
  },
  'vertical-breakout': {
    name: 'vertical-breakout',
    demo: dynamic(
      () => import('@/content/components/breakout/vertical-breakout.demo')
    ),
    file: 'content/components/breakout/vertical-breakout.demo.tsx',
  },
  'button-variant': {
    name: 'button-variant',
    demo: dynamic(
      () => import('@/content/components/button/button-variant.demo')
    ),
    file: 'content/components/button/button-variant.demo.tsx',
  },
  'full-container': {
    name: 'full-container',
    demo: dynamic(
      () => import('@/content/components/container/full-container.demo')
    ),
    file: 'content/components/container/full-container.demo.tsx',
  },
  'small-container': {
    name: 'small-container',
    demo: dynamic(
      () => import('@/content/components/container/small-container.demo')
    ),
    file: 'content/components/container/small-container.demo.tsx',
  },
  'stack-horizontal': {
    name: 'stack-horizontal',
    demo: dynamic(
      () => import('@/content/components/stack/stack-horizontal.demo')
    ),
    file: 'content/components/stack/stack-horizontal.demo.tsx',
  },
  'stack-nested': {
    name: 'stack-nested',
    demo: dynamic(() => import('@/content/components/stack/stack-nested.demo')),
    file: 'content/components/stack/stack-nested.demo.tsx',
  },
  'stack-spacing': {
    name: 'stack-spacing',
    demo: dynamic(
      () => import('@/content/components/stack/stack-spacing.demo')
    ),
    file: 'content/components/stack/stack-spacing.demo.tsx',
  },
  'stack-vertical': {
    name: 'stack-vertical',
    demo: dynamic(
      () => import('@/content/components/stack/stack-vertical.demo')
    ),
    file: 'content/components/stack/stack-vertical.demo.tsx',
  },
} as const;
