// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import dynamic from 'next/dynamic';

export const registry = {
  'basic-accordion': {
    name: 'basic-accordion',
    demo: dynamic(
      () => import('@/content/components/accordion/basic-accordion.demo')
    ),
    file: 'content/components/accordion/basic-accordion.demo.tsx',
  },
  rightside: {
    name: 'rightside',
    demo: dynamic(() => import('@/content/components/aside/rightside.demo')),
    file: 'content/components/aside/rightside.demo.tsx',
  },
  space: {
    name: 'space',
    demo: dynamic(() => import('@/content/components/aside/space.demo')),
    file: 'content/components/aside/space.demo.tsx',
  },
  'button-variant': {
    name: 'button-variant',
    demo: dynamic(
      () => import('@/content/components/button/button-variant.demo')
    ),
    file: 'content/components/button/button-variant.demo.tsx',
  },
  'horizontal-breakout': {
    name: 'horizontal-breakout',
    demo: dynamic(
      () => import('@/content/components/breakout/horizontal-breakout.demo')
    ),
    file: 'content/components/breakout/horizontal-breakout.demo.tsx',
  },
  'iframe-breakout': {
    name: 'iframe-breakout',
    demo: dynamic(
      () => import('@/content/components/breakout/iframe-breakout.demo')
    ),
    file: 'content/components/breakout/iframe-breakout.demo.tsx',
  },
  'vertical-breakout': {
    name: 'vertical-breakout',
    demo: dynamic(
      () => import('@/content/components/breakout/vertical-breakout.demo')
    ),
    file: 'content/components/breakout/vertical-breakout.demo.tsx',
  },
  'collapse-columns': {
    name: 'collapse-columns',
    demo: dynamic(
      () => import('@/content/components/columns/collapse-columns.demo')
    ),
    file: 'content/components/columns/collapse-columns.demo.tsx',
  },
  'layout-columns': {
    name: 'layout-columns',
    demo: dynamic(
      () => import('@/content/components/columns/layout-columns.demo')
    ),
    file: 'content/components/columns/layout-columns.demo.tsx',
  },
  'space-columns': {
    name: 'space-columns',
    demo: dynamic(
      () => import('@/content/components/columns/space-columns.demo')
    ),
    file: 'content/components/columns/space-columns.demo.tsx',
  },
  'stretch-columns-switch': {
    name: 'stretch-columns-switch',
    demo: dynamic(
      () => import('@/content/components/columns/stretch-columns-switch.demo')
    ),
    file: 'content/components/columns/stretch-columns-switch.demo.tsx',
  },
  'stretch-columns': {
    name: 'stretch-columns',
    demo: dynamic(
      () => import('@/content/components/columns/stretch-columns.demo')
    ),
    file: 'content/components/columns/stretch-columns.demo.tsx',
  },
} as const;
