// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import dynamic from 'next/dynamic';

export const Index: Record<string, any> = {
  'button-variant': {
    name: 'button-variant',
    demo: dynamic(
      () => import('@/content/components/button/button-variant.demo')
    ),
    file: 'content/components/button/button-variant.demo.tsx',
  },
  button: {
    name: 'button',
    demo: dynamic(() => import('@/content/components/button/button.demo')),
    file: '',
  },
};
