// Auto-generated by scripts/build-appearances.mjs — DO NOT EDIT
// Run 'pnpm build' in themes/theme-rui to regenerate.

export const appearances = {
  Accordion: {
    variant: ['default', 'card'],
    size: [],
  },
  ActionBar: {
    variant: [],
    size: [],
  },
  Autocomplete: {
    variant: [],
    size: [],
  },
  Badge: {
    variant: [
      'default',
      'primary',
      'success',
      'warning',
      'info',
      'error',
      'admin',
      'master',
    ],
    size: [],
  },
  Breadcrumbs: {
    variant: ['default'],
    size: ['small', 'default', 'large'],
  },
  Button: {
    variant: [
      'primary',
      'secondary',
      'ghost',
      'destructive',
      'destructive-ghost',
      'link',
    ],
    size: ['default', 'small', 'large', 'icon'],
  },
  Calendar: {
    variant: [],
    size: [],
  },
  Card: {
    variant: ['default', 'master', 'admin'],
    size: [],
  },
  Checkbox: {
    variant: [],
    size: [],
  },
  CloseButton: {
    variant: [],
    size: [],
  },
  Collapsible: {
    variant: ['default', 'link'],
    size: ['default'],
  },
  ComboBox: {
    variant: [],
    size: [],
  },
  ContextualHelp: {
    variant: ['help', 'info'],
    size: ['default'],
  },
  DateField: {
    variant: [],
    size: [],
  },
  DatePicker: {
    variant: [],
    size: [],
  },
  Dialog: {
    variant: [],
    size: ['xsmall', 'small', 'medium'],
  },
  Divider: {
    variant: ['default', 'bold'],
    size: [],
  },
  Drawer: {
    variant: [],
    size: ['xsmall', 'small', 'medium'],
  },
  EmptyState: {
    variant: [],
    size: [],
  },
  Field: {
    variant: [],
    size: [],
  },
  FileField: {
    variant: [],
    size: [],
  },
  Headline: {
    variant: [],
    size: ['level-1', 'level-2', 'level-3', 'level-4', 'level-5', 'level-6'],
  },
  HelpText: {
    variant: [],
    size: [],
  },
  IconButton: {
    variant: ['navigation'],
    size: [],
  },
  Input: {
    variant: [],
    size: [],
  },
  Label: {
    variant: [],
    size: [],
  },
  LegacyTable: {
    variant: ['default', 'grid', 'muted', 'admin', 'master'],
    size: [],
  },
  Link: {
    variant: ['default', 'secondary'],
    size: ['default', 'small'],
  },
  LinkButton: {
    variant: [
      'primary',
      'secondary',
      'ghost',
      'destructive',
      'destructive-ghost',
      'link',
    ],
    size: ['default', 'small', 'large', 'icon'],
  },
  List: {
    variant: [],
    size: ['default', 'small'],
  },
  ListBox: {
    variant: [],
    size: [],
  },
  Loader: {
    variant: ['default', 'inverted'],
    size: ['default', 'large', 'fit'],
  },
  Menu: {
    variant: ['default', 'destructive', 'ghost'],
    size: ['default', 'small', 'large', 'icon'],
  },
  Modal: {
    variant: [],
    size: ['xsmall', 'small', 'medium'],
  },
  MultiSelect: {
    variant: [],
    size: [],
  },
  NumberField: {
    variant: [],
    size: [],
  },
  Pagination: {
    variant: [],
    size: [],
  },
  Popover: {
    variant: [],
    size: [],
  },
  ProgressCircle: {
    variant: ['default', 'inverted'],
    size: ['default', 'large', 'fit'],
  },
  Radio: {
    variant: [],
    size: [],
  },
  SectionMessage: {
    variant: ['success', 'warning', 'info', 'error'],
    size: [],
  },
  Select: {
    variant: [],
    size: [],
  },
  Slider: {
    variant: [],
    size: [],
  },
  Switch: {
    variant: [],
    size: [],
  },
  Table: {
    variant: ['default', 'grid', 'muted', 'admin', 'master'],
    size: ['compact', 'default', 'spacious'],
  },
  Tabs: {
    variant: [],
    size: [],
  },
  Tag: {
    variant: [],
    size: [],
  },
  TagField: {
    variant: [],
    size: [],
  },
  Text: {
    variant: ['default', 'muted'],
    size: [
      'default',
      'xs',
      'sm',
      'base',
      'lg',
      'xl',
      '2xl',
      '3xl',
      '4xl',
      '5xl',
      '6xl',
      '7xl',
      '8xl',
      '9xl',
    ],
  },
  TextArea: {
    variant: [],
    size: [],
  },
  Toast: {
    variant: ['default', 'success', 'warning', 'info', 'error'],
    size: [],
  },
  ToggleButton: {
    variant: [],
    size: ['default', 'small', 'icon'],
  },
  ToggleButtonGroup: {
    variant: [],
    size: ['default', 'small', 'icon'],
  },
  Tooltip: {
    variant: ['default', 'white'],
    size: [],
  },
  Tray: {
    variant: [],
    size: [],
  },
  Underlay: {
    variant: [],
    size: [],
  },
} as const;

export type Appearances = typeof appearances;
