name: Coverage

on:
  workflow_run:
    workflows: ['Test']
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.0.0 # Uses version from package.json#packageManager
      - name: Setup Node (using .node-version)
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Generate and check coverage
        uses: davelosert/vitest-coverage-report-action@v2
