name: Deploy Docs

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]
  # workflow_dispatch:
  #   branches:
  #     - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Deploy Docs
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      # Deploy Docs on Vercel
      - name: Ping Vercel
        run: echo ${{ secrets.VERCEL_DEPLOY_DOCS_HOOK }}
