name: Deploy Docs

on:
  workflow_dispatch:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Deploy Docs
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      # Deploy Docs on Vercel
      - name: Ping Vercel
        run: curl $VERCEL_URL
        env:
          VERCEL_URL: ${{ secrets.VERCEL_DEPLOY_DOCS_HOOK }}
