name: Foo

on: ['push']

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Foo
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.32.3
      - name: Setup Node (using .node-version)
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      # Send Slack Notification
      - name: Create release notification
        run: pnpm release:notification -- '[{"name":"@marigold/components","version":"1.1.0"},{"name":"@marigold/system","version":"1.0.0"}]'
      - name: Slack Notification
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload-file-path: './slack-notification.json'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TEST }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
