# on:
#   push:
#     branches:
#       - 1659-release-npm-and-slack-with-github
#   pull_request:
#     branches:
#       - 1659-release-npm-and-slack-with-github
# name: Slack Notification
# jobs:
#   slackNotification:
#     name: Slack Notification
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: pnpm/action-setup@v2.0.1
#         with:
#           version: 6.32.3
#       - name: Setup Node (using .node-version)
#         uses: actions/setup-node@v2
#         with:
#           node-version-file: '.node-version'
#           cache: 'pnpm'
#       - name: Install dependencies
#         run: pnpm install
#       - name: Slack Notification
#         uses: rtCamp/action-slack-notify@v2
#         env:
#           SLACK_COLOR: '#fa8005'
#           SLACK_MESSAGE: ':marigold: <https://github.com/marigold-ui/marigold/blob/main/packages/components/CHANGELOG.md|:marigold: *View Changelog*>'
#           SLACK_TITLE: 'New Release :tada: '
#           SLACK_USERNAME: Marigold
#           MSG_MINIMAL: true
#           SLACK_FOOTER: ''
#           SLACK_WEBHOOK: ${{ secrets.SLACK_TEST }}

on:
  push:
    branches:
      - 1659-release-npm-and-slack-with-github
  pull_request:
    branches:
      - 1659-release-npm-and-slack-with-github
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.3
      - name: Setup Node (using .node-version)
        uses: actions/setup-node@v2
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: Slack Notification
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        - name: Read version from package.json
        uses: culshaw/read-package-version-actions@v1
        id: package-version

      - name: Show node version number
        run: echo "Version is ${{ steps.package-version.outputs.version }}"
        # Version is 12.13.x
        with:
          payload: |
            {
              "text": "New Release from Marigold",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ':information_source: New Release v :tada:'
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Click below to see all *changes*"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": " <https://github.com/marigold-ui/marigold/blob/main/packages/components/CHANGELOG.md|:marigold: *View Changelog*>"
                  }
                }
              ]
            }

        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TEST }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
