# on:
#   push:
#     branches:
#       - 1659-release-npm-and-slack-with-github
#   pull_request:
#     branches:
#       - 1659-release-npm-and-slack-with-github
# name: Slack Notification
# jobs:
#   slackNotification:
#     name: Slack Notification
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: pnpm/action-setup@v2.0.1
#         with:
#           version: 6.32.3
#       - name: Setup Node (using .node-version)
#         uses: actions/setup-node@v2
#         with:
#           node-version-file: '.node-version'
#           cache: 'pnpm'
#       - name: Install dependencies
#         run: pnpm install
#       - name: Slack Notification
#         uses: rtCamp/action-slack-notify@v2
#         env:
#           SLACK_COLOR: '#fa8005'
#           SLACK_MESSAGE: ':marigold: <https://github.com/marigold-ui/marigold/blob/main/packages/components/CHANGELOG.md|:marigold: *View Changelog*>'
#           SLACK_TITLE: 'New Release :tada: '
#           SLACK_USERNAME: Marigold
#           MSG_MINIMAL: true
#           SLACK_FOOTER: ''
#           SLACK_WEBHOOK: ${{ secrets.SLACK_TEST }}

on:
  push:
    branches:
      - 1659-release-npm-and-slack-with-github
  pull_request:
    branches:
      - 1659-release-npm-and-slack-with-github
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.3
      - name: Setup Node (using .node-version)
        uses: actions/setup-node@v2
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Slack Notification
        id: slack
        uses: slackapi/slack-github-action@v1.19.0
        env:
          VERSION: export $("require('../packages/components/package.json').version")
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TEST }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":tada:  New Marigold Release (v${{123}})"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "text": "*${{ steps.date.outputs.date }}*  |  Design System Team",
                      "type": "mrkdwn"
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "For a detailed list of updates, fixes and additions see the latest changelog."
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":point_right: *<https://github.com/marigold-ui/marigold/blob/main/packages/components/CHANGELOG.md#marigoldcomponents|View Changelog>* :point_left:"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "If you find any bugs or have suggestions how we can improve Marigold, please <https://github.com/marigold-ui/marigold/issues/new/choose|let us know>!"
                    }
                  ]
                }
              ]
            }
